# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web Build

on:
  push:
    tags:        
      - w1.*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2

      - name: Install dependencies
        run: flutter pub get 

      - name: Analyze project source
        run: flutter build web

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ./build/web

          
